services:
  db:
    image: postgres:16
    container_name: arena_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
  
  cache:
    image: redis:latest
    container_name: arena_cache
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_db_data:
  redis_data: