name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  EMAIL_PROVIDER: ${{ secrets.EMAIL_PROVIDER }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  STAGE: ${{ secrets.STAGE }}

jobs:
  deploy-production:
    name: Deploy Arena Production
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0 # Fixed indentation
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Create SSH Tunnel
        run: |
          ssh -o StrictHostKeyChecking=no -fN -v -L "$DB_PORT":"$DB_HOST":"$DB_PORT" ${{ secrets.SERVER_SSH_USER }}@${{ secrets.SERVER_HOST_NAME }}

      - name: Sync Database Schema
        env:
          DB_HOST: localhost
        run: |
          bun run db:generate
          bun run db:migrate

      - name: Setup Build Cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
            .next/standalone
          key: app-build-${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            app-build-${{ runner.os }}-

      - name: Build App
        env:
          DB_HOST: localhost
          NEXT_TELEMETRY_DISABLED: 1
        run: bun --bun run build

      - name: Package Artifacts
        run: |
          cp -r .next/standalone ./build
          cp -r .next/static ./build/.next/static

          cd build
          cat <<EOF > app.env
          DB_NAME=$DB_NAME
          DB_HOST=$DB_HOST
          DB_PORT=$DB_PORT
          DB_USER=$DB_USER
          DB_PASS=$DB_PASS
          REDIS_HOST=$REDIS_HOST
          REDIS_PORT=$REDIS_PORT
          AUTH_SECRET=$AUTH_SECRET
          EMAIL_PROVIDER=$EMAIL_PROVIDER
          AWS_REGION=$AWS_REGION
          STAGE=$STAGE
          EOF
          cd ..

          tar czf build.tar.gz ./build

      - name: Deploy To Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST_NAME }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: "./build.tar.gz"
          target: "~/app/tmp"

      - name: Startup New Deployment
        run: |
          ssh -t -o StrictHostKeyChecking=no ${{ secrets.SERVER_SSH_USER }}@${{ secrets.SERVER_HOST_NAME }} '. ~/app/deploy.sh'
